_base_: ./exp1_stage1_3_adacode_v2_long_from_no_prior_cosine.yaml

load_checkpoint:
  exp: exp1_stage1_3_adacode_v2_long_from_no_prior_cosine
  iter: 500000
  load_discriminator: true
  load_scheduler: false
  load_optimizer: true
  new_g_lr: 0.0001
  new_d_lr: 0.0001
  strict: false

model:
  use_selected_beta_pairs: true
  selected_beta_rate: [
    1.921, # 0.050 bpp
    1.312, # 0.075 bpp
    0.844, # 0.100 bpp
    0.422, # 0.125 bpp
    0.091, # 0.150 bpp
  ]
  selected_beta_vq: [
    2.25, # 0.050 bpp
    3.5,  # 0.075 bpp
    3.25, # 0.100 bpp
    0.5,  # 0.125 bpp
    2.25, # 0.150 bpp
  ]

keep_step: [
  400000,
  500000,
]
total_iter: 500000

optim:
  g_scheduler:
    type: MultiStepLR
    milestones: [300000]
    gamma: 0.1
  d_scheduler:
    type: MultiStepLR
    milestones: [300000]
    gamma: 0.1
